set(CMAKE_CROSSCOMPILING TRUE)

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc-9)
set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++-9)
set(CMAKE_AR aarch64-linux-gnu-ar)
SET(CMAKE_LINKER aarch64-linux-gnu-ld)

# cross-compilation libs
set(CMAKE_FIND_ROOT_PATH /usr/aarch64-linux-gnu)
# rpi root, if available
if (DEFINED ENV{RPI_ROOTFS})
    set(CMAKE_SYSROOT $ENV{RPI_ROOTFS})
    set(CMAKE_FIND_ROOT_PATH ${CMAKE_FIND_ROOT_PATH} )
endif ()
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)